name: Check if SIP is enabled

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: Check SIP status
        run: |
          csrutil status
      - name: Check macOS version
        run: |
          sw_vers
      - name: Check Xcode version
        run: |
          xcodebuild -version 
